[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.26"

[fuzz]
runs = 5000
max_test_rejects = 150000

[invariant]
runs = 256
depth = 15
fail_on_revert = false
call_override = false
show_metrics = true